import os
import json
import re
import httpx
import fitz  # PyMuPDF
from groq import Groq
from dotenv import load_dotenv

from fastapi import FastAPI, HTTPException, UploadFile, File
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from bs4 import BeautifulSoup

# Load environment variables from .env file
load_dotenv()


# ─── APP SETUP ────────────────────────────────────────────────────────────────

app = FastAPI(
    title="AnchorAI",
    description="Source-grounded LLM chatbot. Every answer is traceable to a source document.",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

api_key = os.environ.get("GROQ_API_KEY")
if not api_key:
    raise RuntimeError(
        "GROQ_API_KEY environment variable is not set. "
        "Get a free key at console.groq.com"
    )

client = Groq(api_key=api_key)


# ─── REQUEST MODELS ───────────────────────────────────────────────────────────

class FetchURLRequest(BaseModel):
    url: str

class AskRequest(BaseModel):
    question: str
    source: str
    history: list[dict] = []


# ─── SYSTEM PROMPT ────────────────────────────────────────────────────────────
# This is the core of AnchorAI. The entire grounding behavior lives here.
# It instructs the LLM to:
#   (1) Only answer from the provided source
#   (2) Always return the exact excerpt it used
#   (3) Return a confidence score reflecting how well the source supports the answer
#   (4) Refuse gracefully when the answer is not in the source

SYSTEM_PROMPT = """
You are AnchorAI — a question-answering assistant with one strict rule:
you ONLY answer from the SOURCE DOCUMENT provided by the user.
You never use outside knowledge, never speculate, and never hallucinate.

Your output must ALWAYS be a valid JSON object in this exact format:

{
  "found": true or false,
  "answer": "your answer here, or empty string if not found",
  "excerpt": "the exact sentence or passage from the source that supports your answer, or empty string if not found",
  "confidence": a number from 0 to 100 reflecting how directly the source supports the answer
}

Rules you must follow without exception:
- If the answer exists in the source: set found=true, write a clear answer, paste the supporting excerpt verbatim, and score your confidence honestly.
- If the answer is NOT in the source: set found=false, leave answer and excerpt as empty strings, set confidence to 0.
- Never invent or infer beyond what the source explicitly states.
- The excerpt must be copied word-for-word from the source — do not paraphrase it.
- Return ONLY the JSON object. No preamble, no markdown, no explanation outside the JSON.
""".strip()


# ─── UTILITY: CLEAN TEXT EXTRACTION ──────────────────────────────────────────

def extract_clean_text(html: str) -> str:
    soup = BeautifulSoup(html, "html.parser")

    for tag in soup(["script", "style", "nav", "footer", "header",
                     "aside", "form", "noscript", "iframe", "svg"]):
        tag.decompose()

    text = soup.get_text(separator="\n")
    lines = [line.strip() for line in text.splitlines()]
    lines = [line for line in lines if len(line) > 30]
    clean = "\n".join(lines)

    return truncate_to_12k(clean)


# ─── UTILITY: TRUNCATE TEXT ───────────────────────────────────────────────────

def truncate_to_12k(text: str) -> str:
    words = text.split()
    # Use 1.5k words ≈ 2k tokens + system prompt + response = ~3.5k total
    if len(words) > 1500:
        return " ".join(words[:1500]) + "\n\n[Source truncated to fit model limits]"
    return text


# ─── UTILITY: SAFE JSON PARSE ─────────────────────────────────────────────────

def parse_llm_json(raw: str) -> dict:
    # Remove <think> blocks often generated by reasoning models
    raw = re.sub(r"<think>.*?</think>", "", raw, flags=re.DOTALL)
    cleaned = re.sub(r"```(?:json)?", "", raw).replace("```", "").strip()
    
    # Extract just the JSON object in case there's extra text
    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start != -1 and end != -1:
        cleaned = cleaned[start:end+1]
        
    return json.loads(cleaned)


# ─── ROUTES ───────────────────────────────────────────────────────────────────

@app.get("/")
async def serve_frontend():
    """Serve the AnchorAI frontend."""
    return FileResponse("anchorai.html")


@app.get("/health")
async def health_check():
    """Health check endpoint for Azure App Service."""
    return {"status": "ok", "service": "AnchorAI"}


@app.post("/api/fetch-url")
async def fetch_url(request: FetchURLRequest):
    """
    Fetch a URL and return clean extracted text.
    Tries Jina AI Reader first for JS-heavy sites,
    falls back to direct BeautifulSoup fetch for simple HTML.
    """
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/120.0.0.0 Safari/537.36"
        )
    }

    # ── Step 1: Try Jina Reader ───────────────────────────────────────────────
    jina_url = f"https://r.jina.ai/{request.url}"
    try:
        async with httpx.AsyncClient(timeout=20.0, follow_redirects=True) as client:
            jina_response = await client.get(jina_url, headers=headers)
            if jina_response.status_code == 200:
                clean_text = truncate_to_12k(jina_response.text.strip())
                if len(clean_text) > 200:
                    return {
                        "content": clean_text,
                        "word_count": len(clean_text.split()),
                        "url": request.url
                    }
    except Exception:
        pass

    # ── Step 2: Direct fetch fallback ────────────────────────────────────────
    try:
        async with httpx.AsyncClient(timeout=15.0, follow_redirects=True) as client:
            response = await client.get(request.url, headers=headers)
            response.raise_for_status()
    except httpx.TimeoutException:
        raise HTTPException(
            status_code=408,
            detail="URL fetch timed out. Try pasting the text directly."
        )
    except httpx.HTTPStatusError as e:
        raise HTTPException(
            status_code=e.response.status_code,
            detail="Could not fetch URL."
        )
    except Exception:
        raise HTTPException(
            status_code=400,
            detail="Invalid URL or unreachable page."
        )

    content_type = response.headers.get("content-type", "")
    if "application/pdf" in content_type:
        raise HTTPException(
            status_code=415,
            detail="PDF detected. Use the Upload PDF tab instead."
        )
    if "image/" in content_type or "video/" in content_type or "audio/" in content_type:
        raise HTTPException(
            status_code=415,
            detail="Media files are not supported. Paste the text directly instead."
        )

    clean_text = extract_clean_text(response.text)

    if len(clean_text.strip()) < 100:
        raise HTTPException(
            status_code=422,
            detail="Page has too little readable content. Try pasting the text directly."
        )

    return {
        "content": clean_text,
        "word_count": len(clean_text.split()),
        "url": str(response.url)
    }


@app.post("/api/ask")
async def ask(request: AskRequest):
    """
    Answer a question grounded strictly in the provided source.
    Uses a fallback chain of models (Llama 3.1 8B, Qwen, etc) for
    reliable instruction following and JSON output.
    """
    if not request.source or len(request.source.strip()) < 50:
        raise HTTPException(status_code=400, detail="Source content is too short.")

    if not request.question or len(request.question.strip()) < 2:
        raise HTTPException(status_code=400, detail="Question is too short.")

    # Ensure source is within token limits
    source_text = truncate_to_12k(request.source)
    
    # Debug: print actual word count
    word_count = len(source_text.split())
    print(f"Source word count after truncation: {word_count}")

    # Build conversation context
    history_text = ""
    if request.history:
        turns = []
        for turn in request.history[-6:]:
            role = "User" if turn["role"] == "user" else "AnchorAI"
            turns.append(f"{role}: {turn['content']}")
        history_text = "\n".join(turns) + "\n\n"

    prompt = f"""{SYSTEM_PROMPT}

---SOURCE DOCUMENT START---
{source_text}
---SOURCE DOCUMENT END---

{history_text}User question: {request.question}

Respond with ONLY the JSON object."""
    
    # Debug: estimate token count
    estimated_tokens = len(prompt.split()) * 1.33
    print(f"Estimated prompt tokens: {int(estimated_tokens)}")

    models_to_try = [
        "llama-3.1-8b-instant",
        "openai/gpt-oss-20b",
        "groq/compound",
        "qwen/qwen3.6-27b"
    ]
    
    raw = None
    last_error = None
    
    for model in models_to_try:
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.1,
                max_tokens=800,
            )
            raw = response.choices[0].message.content
            break
        except Exception as e:
            print(f"Groq API Error with model {model}: {str(e)}")
            last_error = e
            continue
            
    if raw is None:
        raise HTTPException(status_code=502, detail=f"LLM error: All fallback models failed. Last error: {str(last_error)}")

    try:
        result = parse_llm_json(raw)
    except json.JSONDecodeError as e:
        print(f"JSON Parse Error: {str(e)}")
        print(f"Raw response: {raw}")
        return {
            "found": False,
            "answer": "",
            "excerpt": "",
            "confidence": 0
        }

    return {
        "found": bool(result.get("found", False)),
        "answer": str(result.get("answer", "")),
        "excerpt": str(result.get("excerpt", "")),
        "confidence": min(100, max(0, int(result.get("confidence", 0))))
    }


# ─── PDF PARSING ──────────────────────────────────────────────────────────────

@app.post("/api/parse-pdf-file")
async def parse_pdf_file(file: UploadFile = File(...)):
    """
    Extract clean text from a PDF upload, page by page.
    Uses PyMuPDF — handles complex layouts and embedded fonts.
    """
    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=415, detail="Only PDF files are accepted here.")

    contents = await file.read()

    if len(contents) > 20 * 1024 * 1024:
        raise HTTPException(status_code=413, detail="PDF too large. Please use a file under 20MB.")

    try:
        doc = fitz.open(stream=contents, filetype="pdf")
    except Exception:
        raise HTTPException(
            status_code=422,
            detail="Could not read PDF. File may be corrupted or encrypted."
        )

    pages_text = []
    for page_num, page in enumerate(doc):
        text = page.get_text("text").strip()
        if text:
            pages_text.append(f"[Page {page_num + 1}]\n{text}")

    doc.close()

    if not pages_text:
        raise HTTPException(
            status_code=422,
            detail="No readable text found. This PDF may be scanned or image-based."
        )

    full_text = truncate_to_12k("\n\n".join(pages_text))

    return {
        "content": full_text,
        "page_count": len(pages_text),
        "word_count": len(full_text.split()),
        "filename": file.filename
    }


# ─── STARTUP ──────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)